# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
