# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-29 12:25
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('logo', models.ImageField(default='/var/www/html/agora/static/img/logos/logo-none.jpg', upload_to='/home/thanasis/agora/static/img/logos')),
            ],
            options={
                'verbose_name_plural': '1. Service Components',
            },
        ),
        migrations.CreateModel(
            name='ServiceComponentImplementation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.ServiceComponent')),
            ],
            options={
                'verbose_name_plural': '2. Service Components Implementations',
            },
        ),
        migrations.CreateModel(
            name='ServiceComponentImplementationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, default=None, max_length=255)),
                ('configuration_parameters', ckeditor_uploader.fields.RichTextUploadingField()),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.ServiceComponent')),
                ('component_implementation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.ServiceComponentImplementation')),
            ],
            options={
                'verbose_name_plural': '3. Service Components Implementations Details',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetailsComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_component_implementation_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.ServiceComponentImplementationDetail')),
                ('service_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceDetails')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
            ],
            options={
                'verbose_name_plural': '5. Service Components Implementations Details Link',
            },
        ),
        migrations.AlterUniqueTogether(
            name='servicedetailscomponent',
            unique_together=set([('service_id', 'service_details_id', 'service_component_implementation_detail_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='servicecomponentimplementationdetail',
            unique_together=set([('component_implementation_id', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='servicecomponentimplementation',
            unique_together=set([('component_id', 'name')]),
        ),
    ]
