# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0011_servicedetailscomponent_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecomponent',
            name='logo',
            field=models.ImageField(default=b'service-category-icon-default.jpg', upload_to='components'),
        ),
    ]
