# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0012_auto_20190328_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecomponent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecomponentimplementation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecomponentimplementationdetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicedetailscomponent',
            options={},
        ),
    ]
