# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0013_auto_20190618_0930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicecomponentimplementation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicecomponentimplementation',
            name='component_id',
        ),
        migrations.AlterUniqueTogether(
            name='servicecomponentimplementationdetail',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicecomponentimplementationdetail',
            name='component_id',
        ),
        migrations.RemoveField(
            model_name='servicecomponentimplementationdetail',
            name='component_implementation_id',
        ),
        migrations.AlterUniqueTogether(
            name='servicedetailscomponent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicedetailscomponent',
            name='service_component_implementation_detail_id',
        ),
        migrations.RemoveField(
            model_name='servicedetailscomponent',
            name='service_details_id',
        ),
        migrations.RemoveField(
            model_name='servicedetailscomponent',
            name='service_id',
        ),
        migrations.DeleteModel(
            name='ServiceComponent',
        ),
        migrations.DeleteModel(
            name='ServiceComponentImplementation',
        ),
        migrations.DeleteModel(
            name='ServiceComponentImplementationDetail',
        ),
        migrations.DeleteModel(
            name='ServiceDetailsComponent',
        ),
    ]
