# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_shibboleth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[['observer', 'Observer'], ['serviceowner', 'Service Owner'], ['admin', 'Admin']], default=b'observer', max_length=20),
        ),
    ]
