# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180328_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'avatar'),
        ),
    ]
