# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180402_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[['observer', 'Observer'], ['serviceadmin', 'Service Admin'], ['admin', 'Admin'], ['superadmin', 'Superadmin']], default=b'observer', max_length=20),
        ),
    ]
