# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='accounts.Organisation'),
        ),
    ]
