# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190326_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
