# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190618_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pd_bai_3_legal_entity',
            field=models.BooleanField(default=False, verbose_name=b'PD.BAI.3 Legal entity'),
        ),
    ]
