# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_organisation_pd_bai_3_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pd_bai_3_legal_status',
            field=models.CharField(choices=[['Association', 'Association'], ['Consortium', 'Consortium'], ['Corporation', 'Corporation'], ['ERIC', 'ERIC'], ['European Economic Interest Grouping', 'European Economic Interest Grouping'], ['Foundation', 'Foundation'], ['Grouping', 'Grouping'], ['International or Intergovernmental Organisation or Framework', 'International or Intergovernmental Organisation or Framework'], ['Non-Governmental Organisation', 'Non-Governmental Organisation'], ['Non For Profit Company', 'Non For Profit Company'], ['Partnership', 'Partnership'], ['Private Company', 'Private company'], ['Public Company', 'Public Company'], ['Public Legal Entiry', 'Public Legal Entiry'], ['Public Legal Entiry under Private Law', 'Public Legal Entiry under Private Law'], ['Self Employed', 'Self Employed'], ['Society', 'Society'], ['Trust', 'Trust'], ['Union', 'Union'], ['Not a Legal Entity', 'Not a Legal Entity'], ['Other', 'Other']], default='', max_length=255, verbose_name=b'PB.BAI.3_Legal_Status'),
            preserve_default=False,
        ),
    ]
