# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-28 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_organisation_pd_bai_3_legal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pd_bai_0_id',
            field=models.TextField(blank=True, default=None, null=True, verbose_name=b'PD.BAI.0_ID'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_bai_1_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=b'PD.BAI.1_Name'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_bai_2_abbreviation',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name=b'PD.BAI.2_Abbreviation'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_bai_4_website',
            field=models.TextField(blank=True, default=None, null=True, verbose_name=b'PD.BAI.4_Website'),
        ),
    ]
