# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-29 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200428_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pd_loi_1_street_name_and_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'PD.LOI.1 Street Name and Number'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_loi_2_postal_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=b'PD.LOI.1 Postal Code'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_loi_3_city',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=b'PD.LOI.1 City'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_loi_4_region',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=b'PD.LOI.1 Region'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_loi_5_country_or_territory',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'PD.LOI.1 Country or Territory'),
        ),
    ]
