# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20200427_1440'),
        ('accounts', '0017_auto_20200430_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='main_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_contact_provders', to='owner.ContactInformation'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='public_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_contact_providers', to='owner.ContactInformation'),
        ),
    ]
