# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-05 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200504_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_4_networks',
            field=models.ManyToManyField(blank=True, related_name='networked_providers', to='accounts.Network', verbose_name=b'PD.OTH.4 Networks'),
        ),
    ]
