# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200505_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_5_structure_type',
            field=models.ManyToManyField(blank=True, related_name='structured_providers', to='accounts.Structure', verbose_name=b'PD.OTH.5 Structure Type'),
        ),
    ]
