# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200506_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_3_affiliations',
            field=models.ManyToManyField(blank=True, related_name='affiliated_providers', to='accounts.Affiliation', verbose_name=b'PD.OTH.3 Affiliations'),
        ),
    ]
