# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsfriDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsfriType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_10_national_roadmaps',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name=b'PD.OTH.10 National Roadmaps'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_1_hosting_legal_entity',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name=b'PD.OTH.1 Hosting Legal Entity'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_2_participating_countries',
            field=models.TextField(blank=True, default=None, null=True, verbose_name=b'PD.OTH.2 Participating Countries'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_3_affiliations',
            field=models.ManyToManyField(blank=True, related_name='affiliated_providers', to='accounts.Affiliation', verbose_name=b'PD.OTH.3 Affiliations'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_4_networks',
            field=models.ManyToManyField(blank=True, related_name='networked_providers', to='accounts.Network', verbose_name=b'PD.OTH.4 Networks'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_5_structure_type',
            field=models.ManyToManyField(blank=True, related_name='structured_providers', to='accounts.Structure', verbose_name=b'PD.OTH.5 Structure Type'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_6_esfri_domain',
            field=models.ManyToManyField(blank=True, related_name='esfridomain_providers', to='accounts.EsfriDomain', verbose_name=b'PD.OTH.6 ESFRI Domain'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_7_esfri_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esfritype_providers', to='accounts.EsfriType', verbose_name=b'PD.OTH.7 ESFRI Type'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_8_areas_of_activity',
            field=models.ManyToManyField(blank=True, related_name='activity_providers', to='accounts.Activity', verbose_name=b'PD.OTH.8 ESFRI Areas Of Activity'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_9_societal_grand_challenges',
            field=models.ManyToManyField(blank=True, related_name='challenge_providers', to='accounts.Activity', verbose_name=b'PD.OTH.9 Societal Grand Challenges'),
        ),
    ]
