# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200506_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsfriDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_6_esfri_domain',
            field=models.ManyToManyField(blank=True, related_name='esfridomain_providers', to='accounts.EsfriDomain', verbose_name=b'PD.OTH.6 ESFRI Domain'),
        ),
    ]
