# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200506_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='pd_oth_9_societal_grand_challenges',
            field=models.ManyToManyField(blank=True, related_name='challenge_providers', to='accounts.Challenge', verbose_name=b'PD.OTH.9 Societal Grand Challenges'),
        ),
    ]
