# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200506_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsfriType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_7_esfri_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esfridomain_providers', to='accounts.EsfriType', verbose_name=b'PD.OTH.7 ESFRI Type'),
        ),
    ]
