# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-07 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200506_1054'),
        ('accounts', '0022_auto_20200506_1712'),
    ]

    operations = [
    ]
