# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-08 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20200507_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='name',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='pd_bai_1_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name=b'PD.BAI.1_Name'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='pd_bai_3_legal_status',
            field=models.CharField(blank=True, choices=[['Association', 'Association'], ['Consortium', 'Consortium'], ['Corporation', 'Corporation'], ['ERIC', 'ERIC'], ['European Economic Interest Grouping', 'European Economic Interest Grouping'], ['Foundation', 'Foundation'], ['Grouping', 'Grouping'], ['International or Intergovernmental Organisation or Framework', 'International or Intergovernmental Organisation or Framework'], ['Non-Governmental Organisation', 'Non-Governmental Organisation'], ['Non For Profit Company', 'Non For Profit Company'], ['Partnership', 'Partnership'], ['Private Company', 'Private company'], ['Public Company', 'Public Company'], ['Public Legal Entiry', 'Public Legal Entiry'], ['Public Legal Entiry under Private Law', 'Public Legal Entiry under Private Law'], ['Self Employed', 'Self Employed'], ['Society', 'Society'], ['Trust', 'Trust'], ['Union', 'Union'], ['Not a Legal Entity', 'Not a Legal Entity'], ['Other', 'Other']], default=None, max_length=255, null=True, verbose_name=b'PB.BAI.3_Legal_Status'),
        ),
    ]
