# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200506_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='pd_oth_7_esfri_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name=b'PD.OTH.7 ESFRI Type'),
        ),
    ]
