# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_domain_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pd_cli_1_scientific_domain',
            field=models.ManyToManyField(blank=True, related_name='domain_providers', to='accounts.Domain', verbose_name=b'PD.CLI.1 Scientific Domain'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_cli_2_scientific_subdomain',
            field=models.ManyToManyField(blank=True, related_name='subdomain_providers', to='accounts.Subdomain', verbose_name=b'PD.CLI.2 Scientific Subdomain'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_cli_3_tags',
            field=models.TextField(blank=True, default=None, null=True, verbose_name=b'PD.CLI.2 Scientific Subdomain'),
        ),
    ]
