# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200506_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_8_area_of_activity',
            field=models.ManyToManyField(blank=True, related_name='activity_providers', to='accounts.Activity', verbose_name=b'PD.OTH.8 ESFRI Area Of Activity'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_9_societal_grand_challenge',
            field=models.ManyToManyField(blank=True, related_name='challenge_providers', to='accounts.Activity', verbose_name=b'PD.OTH.9 Societal Grand Challenge'),
        ),
    ]
