# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200506_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='pd_oth_8_area_of_activity',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='pd_oth_9_societal_grand_challenge',
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_8_areas_of_activity',
            field=models.ManyToManyField(blank=True, related_name='activity_providers', to='accounts.Activity', verbose_name=b'PD.OTH.8 ESFRI Areas Of Activity'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_9_societal_grand_challenges',
            field=models.ManyToManyField(blank=True, related_name='challenge_providers', to='accounts.Activity', verbose_name=b'PD.OTH.9 Societal Grand Challenges'),
        ),
    ]
