# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-08 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200508_0719'),
        ('accounts', '0024_auto_20200508_1107'),
    ]

    operations = [
    ]
