# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200506_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_10_national_roadmpas',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name=b'PD.OTH.10 National Roadmaps'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_1_hosting_legal_entity',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name=b'PD.OTH.1 Hosting Legal Entity'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pd_oth_2_participating_countries',
            field=models.TextField(blank=True, default=None, null=True, verbose_name=b'PD.OTH.2 Participating Countries'),
        ),
    ]
