# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_merge_20200508_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='abbreviation',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
