# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200506_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='pd_oth_10_national_roadmpas',
            new_name='pd_oth_10_national_roadmaps',
        ),
    ]
