# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200512_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='abbreviation',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
