# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200506_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='pd_oth_7_esfri_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esfritype_providers', to='accounts.EsfriType', verbose_name=b'PD.OTH.7 ESFRI Type'),
        ),
    ]
