# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-29 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200529_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='epp_bai_0_id',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_bai_1_name',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_bai_2_abbreviation',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_bai_3_legal_entity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_bai_3_legal_status',
            field=models.CharField(blank=True, choices=[['Association', 'Association'], ['Consortium', 'Consortium'], ['Corporation', 'Corporation'], ['ERIC', 'ERIC'], ['European Economic Interest Grouping', 'European Economic Interest Grouping'], ['Foundation', 'Foundation'], ['Grouping', 'Grouping'], ['International or Intergovernmental Organisation or Framework', 'International or Intergovernmental Organisation or Framework'], ['Non-Governmental Organisation', 'Non-Governmental Organisation'], ['Non For Profit Company', 'Non For Profit Company'], ['Partnership', 'Partnership'], ['Private Company', 'Private company'], ['Public Company', 'Public Company'], ['Public Legal Entiry', 'Public Legal Entiry'], ['Public Legal Entiry under Private Law', 'Public Legal Entiry under Private Law'], ['Self Employed', 'Self Employed'], ['Society', 'Society'], ['Trust', 'Trust'], ['Union', 'Union'], ['Not a Legal Entity', 'Not a Legal Entity'], ['Other', 'Other']], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_bai_4_website',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_cli_3_tags',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_mti_1_life_cycle_status',
            field=models.CharField(blank=True, choices=[['Under Construction', 'Under Construction'], ['Operational', 'Operational'], ['Being Upgraded', 'Being Upgraded'], ['Other', 'Other']], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_mti_2_certifications',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_oth_1_hosting_legal_entity',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='epp_oth_2_participating_countries',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
