# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200604_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_4_website',
            new_name='epp_bai_3_website',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_3_legal_entity',
            new_name='epp_bai_4_legal_entity',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='epp_bai_3_legal_status',
        ),
        migrations.AddField(
            model_name='organisation',
            name='epp_bai_5_legal_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legalstatus_providers', to='accounts.LegalStatus'),
        ),
    ]
