# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200604_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerilDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerilSubdomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merildomain_merilsubdomain', to='accounts.MerilDomain')),
            ],
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_4_website',
            new_name='epp_bai_3_website',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_3_legal_entity',
            new_name='epp_bai_4_legal_entity',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_oth_8_areas_of_activity',
            new_name='epp_oth_10_areas_of_activity',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_oth_9_societal_grand_challenges',
            new_name='epp_oth_11_societal_grand_challenges',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_oth_10_national_roadmaps',
            new_name='epp_oth_12_national_roadmaps',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='epp_bai_3_legal_status',
        ),
        migrations.AddField(
            model_name='organisation',
            name='epp_bai_5_legal_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legalstatus_providers', to='accounts.LegalStatus'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='epp_oth_8_meril_scientific_domain',
            field=models.ManyToManyField(blank=True, related_name='meril_domain_providers', to='accounts.MerilDomain'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='epp_oth_9_meril_scientific_subdomain',
            field=models.ManyToManyField(blank=True, related_name='meril_subdomain_providers', to='accounts.MerilSubdomain'),
        ),
    ]
