# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-12 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20200611_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_oth_8_areas_of_activity',
            new_name='epp_oth_10_areas_of_activity',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_oth_9_societal_grand_challenges',
            new_name='epp_oth_11_societal_grand_challenges',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_oth_10_national_roadmaps',
            new_name='epp_oth_12_national_roadmaps',
        ),
    ]
