# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20200615_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='esfridomain',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
