# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200612_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerilDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerilSubdomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merildomain_merilsubdomain', to='accounts.MerilDomain')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='epp_oth_8_meril_scientific_domain',
            field=models.ManyToManyField(blank=True, related_name='meril_domain_providers', to='accounts.MerilDomain'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='epp_oth_9_meril_scientific_subdomain',
            field=models.ManyToManyField(blank=True, related_name='meril_subdomain_providers', to='accounts.MerilSubdomain'),
        ),
    ]
