# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_structure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[['observer', 'Observer'], ['serviceadmin', 'Service Admin'], ['provideradmin', 'Provider Admin'], ['superadmin', 'Superadmin']], default=b'observer', max_length=20),
        ),
    ]
