# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-15 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200612_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merilsubdomain',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
