# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200729_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='state',
            field=models.CharField(choices=[['draft', 'Draft'], ['pending', 'Pending'], ['published', 'Published']], default=b'draft', max_length=30),
        ),
    ]
