# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210210_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='eosc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
