# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-03 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_organisation_eosc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='eosc_published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='eosc_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
