# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-03-22 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20210303_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
