# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='epp_mti_2_certifications',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
