# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210514_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provideraudittable', to='accounts.Organisation')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='provideraudit',
            unique_together=set([('provider', 'updated_at')]),
        ),
    ]
