# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20210525_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[['observer', 'Observer'], ['serviceadmin', 'Service Admin'], ['provideradmin', 'Provider Admin'], ['portfolioadmin', 'Portfolio Admin'], ['superadmin', 'Superadmin']], default=b'observer', max_length=20),
        ),
    ]
