# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-28 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20220118_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_oth_1_hosting_legal_entity',
            new_name='epp_bai_hosting_legal_entity',
        ),
    ]
