# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-28 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20220328_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_2_abbreviation',
            new_name='epp_bai_abbreviation',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_0_id',
            new_name='epp_bai_id',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_4_legal_entity',
            new_name='epp_bai_legal_entity',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_5_legal_status',
            new_name='epp_bai_legal_status',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_1_name',
            new_name='epp_bai_name',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_bai_3_website',
            new_name='epp_bai_website',
        ),
    ]
