# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-05 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20220328_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_mri_1_description',
            new_name='epp_mri_description',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_mri_2_logo',
            new_name='epp_mri_logo',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_mri_3_multimedia',
            new_name='epp_mri_multimedia',
        ),
    ]
