# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-04 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20220328_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_cli_1_scientific_domain',
            new_name='epp_cli_scientific_domain',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_cli_2_scientific_subdomain',
            new_name='epp_cli_scientific_subdomain',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_oth_structure_type',
            new_name='epp_cli_structure_type',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_cli_3_tags',
            new_name='epp_cli_tags',
        ),
    ]
