# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-05 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20220405_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='epp_mri_multimedia_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
