# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-07 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20220404_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_loi_1_street_name_and_number',
            new_name='epp_loi_street_name_and_number',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_loi_3_city',
            new_name='epp_loi_city',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_loi_2_postal_code',
            new_name='epp_loi_postal_code',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_loi_4_region',
            new_name='epp_loi_region',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_loi_5_country_or_territory',
            new_name='epp_loi_country_or_territory',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_mri_1_description',
            new_name='epp_mri_description',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_mri_2_logo',
            new_name='epp_mri_logo',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_mri_3_multimedia',
            new_name='epp_mri_multimedia',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_mti_2_certifications',
            new_name='epp_mti_certifications',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='epp_mti_1_life_cycle_status',
            new_name='epp_mti_life_cycle_status',
        ),
    ]
