const countries = [
  'Worldwide',
  'Europe',
  'Åland Islands',
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Channel Islands',
  'Chile',
  'China',
  'China, Hong Kong Special Administrative Region',
  'China, Macao Special Administrative Region',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  'Côte d&amp;Ivoire',
  'Democratic People\'s Republic of Korea',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Holy See',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People\'s Democratic Republic',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of Korea',
  'Republic of Moldova',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Sark',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'State of Palestine',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen Islands',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland',
  'United Republic of Tanzania',
  'United States Virgin Islands',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Wallis and Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

const disciplines = [
  'Accelerator physics',
  'Acoustics',
  'Aerobiology',
  'Aeronautical engineering',
  'Aerosol physics',
  'Aerospace engineering',
  'Agricultural Sciences',
  'Agricultural biotechnology',
  'Agriculture',
  'Agriculture forestry and fisheries',
  'Agronomy/plant breeding/plant protection',
  'Algorithms',
  'Allergy',
  'Anaesthesiology',
  'Analytical chemistry',
  'Anatomy and morphology',
  'Andrology',
  'Animal and dairy sciences',
  'Animal science',
  'Anthropology',
  'Applied mechanics',
  'Archaeology',
  'Architectural design',
  'Architecture engineering',
  'Artificial Intelligence (expert systems\,machine learning\, robotics)',
  'Arts',
  'Astrobiology',
  'Astronautical engineering',
  'Astronomy',
  'Astroparticle physics',
  'Astrophysics',
  'Atmospheric science',
  'Atomic',
  'Audio engineering',
  'Bacteriology',
  'Basic medicine',
  'Behavioural biology',
  'Bio-derived novel materials',
  'Biocatalysis',
  'Biochemistry and molecular biology',
  'Bioderived bulk and fine chemicals',
  'Biodiversity conservation',
  'Bioengineering',
  'Bioengineering and Biomedical engineering',
  'Biofuels',
  'Bioinformatics',
  'Biological Psychology',
  'Biological rhythm',
  'Biology',
  'Biomass feedstock production tech.',
  'Biomaterials',
  'Biomedical devices',
  'Biomedical engineering',
  'Biopharming',
  'Biophysical manipulation',
  'Biophysics',
  'Bioprocessing technologies',
  'Bioproducts',
  'Bioremediation',
  'Biotechnology and medical ethics',
  'Botany',
  'Business and Management',
  'Canon Law',
  'Cardiac and Cardiovascular systems',
  'Cell biology',
  'Ceramics',
  'Chemical engineering',
  'Chemical engineering (plants/products)',
  'Chemical physics',
  'Chemical process engineering',
  'Chemistry',
  'Civil Law',
  'Civil Protection',
  'Civil engineering',
  'Climate research',
  'Clinical Psychology',
  'Clinical medicine',
  'Coating and films',
  'Cognitive Psychology',
  'Colloid chemistry',
  'Communication engineering and systems',
  'Comparative Law',
  'Comparative Psychology',
  'Comparative politics',
  'Competition Law',
  'Composites',
  'Computational biology',
  'Computational chemistry',
  'Computational physics',
  'Computer architecture',
  'Computer communications',
  'Computer graphics',
  'Computer hardware and architecture',
  'Computer security and reliability',
  'Condensed matter physics',
  'Constitutional Law',
  'Construction/Structural engineering',
  'Criminal Law',
  'Critical care/Emergency medicine',
  'Cryobiology',
  'Cryogenics',
  'Cultural and economic geography',
  'Dairy science',
  'Data management',
  'Data mining',
  'Data structures',
  'Demography',
  'Dentistry, oral surgery/medicine',
  'Dermatology and venereal diseases',
  'Developmental Psychology',
  'Developmental biology',
  'Diagnostic biotechnologies',
  'Diagnostics',
  'Distributed computing',
  'Ecology',
  'Economics and Econometrics',
  'Economics finance and business',
  'Educational and School Psychology',
  'Educational sciences',
  'Electrical and electronic engineering',
  'Electrical, electronic and information engineering',
  'Electrochemistry',
  'Empirical pata analysis',
  'Energy and fuels',
  'Environmental biotechnology',
  'Environmental engineering',
  'Epidemiology',
  'Ethics',
  'Ethnology',
  'Evolutionary Psychology',
  'Evolutionary biology',
  'Family studies',
  'Fermentation',
  'Finance',
  'Fishery',
  'Fluid Mechanics',
  'Folklore studies',
  'Food biotechnology',
  'Forestry',
  'Fusion',
  'GM technology (crops/livestock)',
  'Gastroenterology and hepatology',
  'General Education',
  'General and internal medicine',
  'General language studies',
  'General literature studies',
  'Genetics and heredity',
  'Geochemistry',
  'Geological engineering',
  'Geology',
  'Geophysics',
  'Geotechnics',
  'Geriatrics and gerontology',
  'Health care science and services',
  'Health policy and services',
  'Health sciences',
  'Health-related biotechnology',
  'Hematology',
  'High energy physics',
  'History (Prehistory; Ancient; Modern world)',
  'History and Archaeology',
  'Horticulture and viticulture',
  'Human genetics',
  'Human-computer interaction',
  'Humanities',
  'Husbandry',
  'Hydrology',
  'Immunology',
  'Industrial biotechnology',
  'Industrial relations',
  'Industrial–organisational Psychology',
  'Infectious diseases',
  'Information management',
  'Information retrieval',
  'Information science - social',
  'Inorganic and nuclear chemistry',
  'Integrative and Complementary medicine',
  'International relations',
  'Islamic Law',
  'Jewish Law',
  'Journalism',
  'Jurisprudence (Philosophy of Law)',
  'Knowledge management',
  'Languages and literature',
  'Law',
  'Library science',
  'Linguistics',
  'Literary theory',
  'Livestock cloning',
  'Marine and Freshwater biology',
  'Marker assisted selection',
  'Materials engineering',
  'Mathematical biology',
  'Mathematical chemistry',
  'Mathematical physics',
  'Mechanical engineering',
  'Media Studies (Film/Radio/TV)',
  'Media and communications',
  'Media and socio-cultural communication',
  'Medical and Health Sciences',
  'Medical biotechnology',
  'Medical ethics',
  'Medical imaging',
  'Medical physics',
  'Medicinal chemistry',
  'Microbiology',
  'Mineralogy',
  'Mining and mineral processing',
  'Molecular diagnostics',
  'Molecular physics',
  'Multimedia/hypermedia',
  'Musicology',
  'Mycology',
  'Nano-materials',
  'Nano-processes',
  'Nano-technology',
  'Neuroscience',
  'Nuclear medicine',
  'Nuclear physics',
  'Nuclear related engineering',
  'Nursing',
  'Nutrition and Dietetics',
  'Obstetrics and gynaecology',
  'Occupational health',
  'Ocean engineering',
  'Oceanography',
  'Oncology',
  'Operating systems',
  'Ophthalmology',
  'Optics',
  'Optometry',
  'Organic chemistry',
  'Organisation theory',
  'Orthopaedics',
  'Other',
  'Otorhinolaryngology',
  'Paediatrics',
  'Palaeontology',
  'Paper and wood',
  'Parallel computing',
  'Parasitology',
  'Particle physics',
  'Pathology',
  'Performing arts studies',
  'Peripheral vascular disease',
  'Personality Psychology',
  'Petroleum engineering',
  'Pets',
  'Pharmaceutical biotechnology',
  'Pharmacology and pharmacy',
  'Philosophy',
  'Philosophy ethics and religion',
  'Philosophy of science/technology',
  'Physical chemistry',
  'Physical geography',
  'Physics',
  'Physiology',
  'Planetary science',
  'Plant science',
  'Plasma physics',
  'Political economy',
  'Political philosophy',
  'Political sciences',
  'Polymer science',
  'Positive Psychology',
  'Programming languages',
  'Psychiatry',
  'Psychology',
  'Public administration',
  'Public and environmental health',
  'Pure mathematics',
  'Quantum computing',
  'Quantum physics',
  'Radiology',
  'Reliability analysis',
  'Religious studies',
  'Remote sensing',
  'Reproductive biology',
  'Respiratory systems',
  'Rheumatology',
  'Robotics Automation and Control Systems',
  'Sea vessels',
  'Seismology',
  'Social Psychology',
  'Social Sciences',
  'Social and economic geography',
  'Social biomedical science',
  'Social issues',
  'Social work',
  'Sociology',
  'Sociology',
  'Software engineering',
  'Soil science',
  'Space science',
  'Special Education (learning disabilities)',
  'Specific languages',
  'Specific literatures',
  'Sport and fitness science',
  'Statistics and probability',
  'Structural biology',
  'Substance abuse',
  'Surgery',
  'Taxonomy',
  'Textiles',
  'Theology',
  'Theoretical biology',
  'Theories of the state',
  'Theory of computation',
  'Thermal biology',
  'Thermodynamics',
  'Toxicology',
  'Transplantation',
  'Transport engineering',
  'Transport planning',
  'Tropical medicine',
  'Urban studies',
  'Urology and nephrology',
  'Veterinary anaesthesiology',
  'Veterinary medicine',
  'Veterinary ophthalmology',
  'Veterinary pathobiology',
  'Veterinary radiology',
  'Veterinary reproduction',
  'Veterinary sciences',
  'Veterinary surgery',
  'Virology',
  'Volcanology',
  'Women\'s and gender studies',
  'Zoology',
];

const language_codes = [
  'ab',
  'aa',
  'af',
  'ak',
  'sq',
  'am',
  'ar',
  'an',
  'hy',
  'as',
  'av',
  'ae',
  'ay',
  'az',
  'bm',
  'ba',
  'eu',
  'be',
  'bn',
  'bh',
  'bi',
  'bs',
  'br',
  'bg',
  'my',
  'ca',
  'km',
  'ch',
  'ce',
  'ny',
  'zh',
  'cu',
  'cv',
  'kw',
  'co',
  'cr',
  'hr',
  'cs',
  'da',
  'dv',
  'nl',
  'dz',
  'en',
  'eo',
  'et',
  'ee',
  'fo',
  'fj',
  'fi',
  'fr',
  'ff',
  'gd',
  'gl',
  'lg',
  'ka',
  'de',
  'el',
  'gn',
  'gu',
  'ht',
  'ha',
  'he',
  'hz',
  'hi',
  'ho',
  'hu',
  'is',
  'io',
  'ig',
  'id',
  'ia',
  'ie',
  'iu',
  'ik',
  'ga',
  'it',
  'ja',
  'jv',
  'kl',
  'kn',
  'kr',
  'ks',
  'kk',
  'ki',
  'rw',
  'ky',
  'kv',
  'kg',
  'ko',
  'kj',
  'ku',
  'lo',
  'la',
  'lv',
  'li',
  'ln',
  'lt',
  'lu',
  'lb',
  'mk',
  'mg',
  'ms',
  'ml',
  'mt',
  'gv',
  'mi',
  'mr',
  'mh',
  'mn',
  'na',
  'nv',
  'ng',
  'ne',
  'nd',
  'se',
  'no',
  'nb',
  'nn',
  'oc',
  'oj',
  'or',
  'om',
  'os',
  'pi',
  'ps',
  'fa',
  'pl',
  'pt',
  'pa',
  'qu',
  'ro',
  'rm',
  'rn',
  'ru',
  'sm',
  'sg',
  'sa',
  'sc',
  'sr',
  'sn',
  'ii',
  'sd',
  'si',
  'sk',
  'sl',
  'so',
  'nr',
  'st',
  'es',
  'su',
  'sw',
  'ss',
  'sv',
  'tl',
  'ty',
  'tg',
  'ta',
  'tt',
  'te',
  'th',
  'bo',
  'ti',
  'to',
  'ts',
  'tn',
  'tr',
  'tk',
  'tw',
  'ug',
  'uk',
  'ur',
  'uz',
  've',
  'vi',
  'vo',
  'wa',
  'cy',
  'fy',
  'wo',
  'xh',
  'yi',
  'yo',
  'za',
  'zu',
];

export {
  countries,
  disciplines,
  language_codes,
}
