# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shibboleth_id',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
