# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 12:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
import common.helper
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180827_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('logo', models.ImageField(upload_to=common.helper.organisation_image_path)),
            ],
        ),
    ]
