# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_auto_20170922_1215'),
        ('component', '0006_auto_20170926_1431'),
    ]

    operations = [
    ]
