# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0009_auto_20180328_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecomponent',
            name='logo',
            field=models.ImageField(default=b'service-area-icon-default.jpg', upload_to='components'),
        ),
    ]
