# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0010_auto_20180402_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetailscomponent',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, unique=True),
        ),
    ]
