# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170630_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_trl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceTrl'),
        ),
    ]
