# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_service_trl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetrl',
            options={'ordering': ['order'], 'verbose_name_plural': '1. Service Technology Readiness Level'},
        ),
    ]
