# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-18 10:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170630_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicearea',
            options={'verbose_name_plural': '6. Service Areas (settings)'},
        ),
        migrations.AlterModelOptions(
            name='servicestatus',
            options={'ordering': ['order'], 'verbose_name_plural': '8. Service Status (settings)'},
        ),
        migrations.AlterModelOptions(
            name='servicetrl',
            options={'ordering': ['order'], 'verbose_name_plural': '9. Service Technology Readiness Level (settings)'},
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
