# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20170718_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': '7. User Roles',
            },
        ),
        migrations.AlterField(
            model_name='usercustomer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.UserRole'),
        ),
    ]
