# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20170731_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(default='/var/www/html/agora/static/img/logos/logo-none.jpg', upload_to='/home/kostas/Agora/static/img/logos'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='icon',
            field=models.ImageField(default='/var/www/html/agora/static/img/logos/logo-none.jpg', upload_to='/home/kostas/Agora/static/img/logos'),
        ),
    ]
