# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 12:49
from __future__ import unicode_literals

import common.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20180209_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(default=b'service-logo-default.jpg', upload_to=common.helper.service_image_path),
        ),
    ]
