# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20180320_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceownership',
            name='state',
            field=models.CharField(choices=[['pending', 'Pending'], ['approved', 'Approved'], ['rejected', 'Rejected']], default='pending', max_length=30),
        ),
    ]
