# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20180518_0757'),
        ('service', '0021_auto_20180507_1213'),
    ]

    operations = [
    ]
