# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_servicedetails_access_policies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetails',
            old_name='usage_policy_has',
            new_name='terms_of_use_has',
        ),
        migrations.RenameField(
            model_name='servicedetails',
            old_name='usage_policy_url',
            new_name='terms_of_use_url',
        ),
    ]
