# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_auto_20190327_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceArea',
            new_name='ServiceCategory'
        ),
        migrations.RenameField(
            model_name='Service',
            old_name='service_area',
            new_name='service_category'
        ),
    ]
