# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_serviceprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicestatus',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicestatus',
            name='order',
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
