# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 14:34
from __future__ import unicode_literals

from django.db import migrations


def fill_service_categories(apps, schema_editor):
    Service = apps.get_model('service', 'Service')
    for service in Service.objects.all():
        if service.service_category:
            service.service_categories.add(service.service_category)


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_auto_20190403_1431'),
    ]

    operations = [
        migrations.RunPython(fill_service_categories),
    ]
