# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_auto_20190403_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='scientific_fields',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
