# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0040_auto_20190405_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='training_information',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
