# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0042_auto_20190405_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='service_trl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceTrl'),
        ),
    ]
