# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0044_description_external_to_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='accounting_has',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='business_continuity_plan_has',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='decommissioning_procedure_has',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='disaster_recovery_plan_has',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='monitoring_has',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='operations_documentation_has',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='privacy_policy_has',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='terms_of_use_has',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='user_documentation_has',
            field=models.NullBooleanField(default=False),
        ),
    ]
