# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 12:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0045_auto_20190510_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='other_related_services',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='other_required_services',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='related_platform',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='set_as_related_by', to='service.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='required_services',
            field=models.ManyToManyField(blank=True, related_name='is_required_by', to='service.Service'),
        ),
    ]
