# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 08:43
from __future__ import unicode_literals

import re
from django.db import migrations


def description_tagline_transfer(apps, schema_editor):
    Service = apps.get_model('service', 'Service')
    for s in Service.objects.all():
        s.tagline = re.sub('<[^<]+?>', '', s.short_description)
        s.short_description = s.description_external
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0046_auto_20190513_1251'),
    ]

    operations = [
        migrations.RunPython(description_tagline_transfer),
    ]
