# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0047_description_tagline_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalservice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service_dependson_service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicetrl',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usercustomer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={},
        ),
    ]
