# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 08:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0048_auto_20190618_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
