# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0049_servicecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadminship',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceadminships', to='service.Service'),
        ),
    ]
