# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0052_auto_20190903_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.Service'),
        ),
    ]
