# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-24 08:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0055_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
            ],
        ),
    ]
