# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-24 11:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0056_targetuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='rd_mri_1_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='rd_mri_2_tagline',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='rd_mri_3_logo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='rd_mri_4_mulitimedia',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='rd_mri_5_target_users',
            field=models.ManyToManyField(blank=True, to='service.TargetUser'),
        ),
        migrations.AddField(
            model_name='resource',
            name='rd_mri_6_target_customer_tags',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='rd_mri_7_use_cases',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
