# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-27 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0057_auto_20200424_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='rd_gla_1_geographical_availability',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='rd_gla_2_language',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
