# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0059_auto_20200427_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAdminship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[['pending', 'Pending'], ['approved', 'Approved'], ['rejected', 'Rejected']], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourceadminships', to='service.Resource')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resourceadminship',
            unique_together=set([('resource', 'admin')]),
        ),
    ]
