# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0065_auto_20200509_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='rd_cli_3_category',
            field=models.ManyToManyField(blank=True, related_name='categorized_resources', to='service.Category', verbose_name='RD.CLI.3 Category'),
        ),
        migrations.AddField(
            model_name='resource',
            name='rd_cli_4_subcategory',
            field=models.ManyToManyField(blank=True, related_name='subcategorized_resources', to='service.Subcategory', verbose_name='RD.CLI.4 Subcategory'),
        ),
    ]
