# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-28 13:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0067_auto_20200528_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='rd_bai_0_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_bai_1_name',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_bai_2_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_services', to='accounts.Organisation'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_bai_3_providers',
            field=models.ManyToManyField(blank=True, related_name='provided_services', to='accounts.Organisation'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_bai_4_webpage',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_cli_1_scientific_domain',
            field=models.ManyToManyField(blank=True, related_name='domain_resources', to='accounts.Domain'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_cli_2_scientific_subdomain',
            field=models.ManyToManyField(blank=True, related_name='subdomain_resources', to='accounts.Subdomain'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_cli_3_category',
            field=models.ManyToManyField(blank=True, related_name='categorized_resources', to='service.Category'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_cli_4_subcategory',
            field=models.ManyToManyField(blank=True, related_name='subcategorized_resources', to='service.Subcategory'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_gla_1_geographical_availability',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_gla_2_language',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_1_helpdesk_webpage',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_2_helpdesk_email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_3_user_manual',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_4_terms_of_use',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_5_privacy_policy',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_6_sla_specification',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_7_training_information',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_8_status_monitoring',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mgi_9_maintenance',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mri_1_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mri_2_tagline',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mri_3_logo',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mri_4_mulitimedia',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mri_5_target_users',
            field=models.ManyToManyField(blank=True, to='service.TargetUser'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mri_6_target_customer_tags',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rd_mri_7_use_cases',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
