# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0068_auto_20200528_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='rd_cli_5_tags',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
