# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-04 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0070_auto_20200529_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='erp_bai_0_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='erp_bai_1_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
