# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-05 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0071_auto_20200604_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='erp_mri_5_target_users',
            new_name='erp_cli_5_target_users',
        ),
    ]
