# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0072_auto_20200605_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='erp_mri_6_target_customer_tags',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='erp_mri_7_use_cases',
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_mri_5_use_cases',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
