# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0074_auto_20200605_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='erp_coi_13_helpdesk_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_coi_14_security_contact_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
