# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0075_auto_20200605_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='erp_dei_3_related_platforms',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='related_resources',
            field=models.ManyToManyField(blank=True, related_name='set_as_related_by', to='service.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='required_resources',
            field=models.ManyToManyField(blank=True, related_name='is_required_by', to='service.Resource'),
        ),
    ]
