# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0077_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='erp_aoi_1_order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='service.OrderType'),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_aoi_2_order',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
