# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-10 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0079_fundingbody_fundingprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='erp_ati_1_funding_body',
            field=models.ManyToManyField(blank=True, related_name='funded_body_resources', to='service.FundingBody'),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_ati_2_funding_program',
            field=models.ManyToManyField(blank=True, related_name='funded_program_resources', to='service.FundingProgram'),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_ati_3_grant_project_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
