# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0082_auto_20200610_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='erp_cli_8_tags',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
