# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0084_accessmode_accesstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='erp_cli_6_access_type',
            field=models.ManyToManyField(blank=True, to='service.AccessType'),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_cli_7_access_mode',
            field=models.ManyToManyField(blank=True, to='service.AccessMode'),
        ),
    ]
