# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0085_auto_20200611_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='erp_rli_1_geographic_location',
            field=models.TextField(blank=True, default='Other', null=True),
        ),
    ]
