# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-12 12:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0087_lifecyclestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='erp_mti_1_technology_readiness_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.TRL'),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_mti_2_life_cycle_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.LifeCycleStatus'),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_mti_3_certifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_mti_4_standards',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_mti_5_open_source_technologies',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_mti_6_version',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_mti_7_last_update',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='erp_mti_8_changelog',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
