# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-12 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0088_auto_20200612_1256'),
        ('service', '0086_resource_erp_rli_1_geographic_location'),
    ]

    operations = [
    ]
