# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0089_merge_20200612_1315'),
    ]
    run_before = [
        ('owner', '0008_remove_serviceowner_id_service_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id_service_owner',
        ),
    ]
