# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0090_remove_service_id_service_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='id_service',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='id_user',
        ),
        migrations.AlterUniqueTogether(
            name='service_dependson_service',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='service_dependson_service',
            name='id_service_one',
        ),
        migrations.RemoveField(
            model_name='service_dependson_service',
            name='id_service_two',
        ),
        migrations.AlterUniqueTogether(
            name='service_externalservice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='service_externalservice',
            name='id_external_service',
        ),
        migrations.RemoveField(
            model_name='service_externalservice',
            name='id_service',
        ),
        migrations.RemoveField(
            model_name='usercustomer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usercustomer',
            name='service_id',
        ),
        migrations.DeleteModel(
            name='ExternalService',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Service_DependsOn_Service',
        ),
        migrations.DeleteModel(
            name='Service_ExternalService',
        ),
        migrations.DeleteModel(
            name='UserCustomer',
        ),
    ]
