# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0094_delete_servicestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id_contact_information',
        ),
        migrations.RemoveField(
            model_name='service',
            name='id_contact_information_internal',
        ),
        migrations.RemoveField(
            model_name='service',
            name='organisations',
        ),
        migrations.RemoveField(
            model_name='service',
            name='related_services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='required_services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_categories',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_trl',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
