# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0095_auto_20200720_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessPolicy',
        ),
        migrations.DeleteModel(
            name='FederationMember',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceTrl',
        ),
    ]
