# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-04 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0096_auto_20200720_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='main_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_contact_services', to='owner.ContactInformation'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='public_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_contact_services', to='owner.ContactInformation'),
        ),
    ]
