# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0097_auto_20200804_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='state',
            field=models.CharField(choices=[['draft', 'Draft'], ['pending', 'Pending'], ['published', 'Published']], default='draft', max_length=30),
        ),
    ]
