# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0098_resource_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='erp_bai_2_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_services', to='accounts.Organisation'),
        ),
    ]
