# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0103_resource_eosc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='eosc_published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='eosc_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
