# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0104_auto_20210226_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='eosc_published',
            new_name='eosc_published_at',
        ),
    ]
