# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-26 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0107_auto_20210525_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='erp_mri_4_mulitimedia',
            new_name='erp_mri_4_multimedia',
        ),
    ]
