# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-22 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0107_auto_20210525_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='erp_bai_0_id',
            new_name='erp_bai_id',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='erp_bai_1_name',
            new_name='erp_bai_name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='erp_bai_2_organisation',
            new_name='erp_bai_organisation',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='erp_bai_3_providers',
            new_name='erp_bai_providers',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='erp_bai_4_webpage',
            new_name='erp_bai_webpage',
        ),
    ]
