# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-06 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0107_auto_20210525_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='erp_mgi_3_terms_of_use',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='erp_mgi_4_privacy_policy',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
