# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-26 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0108_auto_20220526_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='erp_mri_4_multimedia',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
