# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-27 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0109_resource_erp_bai_abbreviation'),
        ('service', '0109_auto_20220526_0716'),
    ]

    operations = [
    ]
