# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTrl',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(default=None, max_length=255)),
                ('order', models.IntegerField(default=None)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': '1. Service TRL',
            },
        ),
        migrations.AlterModelOptions(
            name='servicestatus',
            options={'ordering': ['order'], 'verbose_name_plural': '1. Service Status'},
        ),
    ]
