# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-31 14:26
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20170720_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalservice',
            options={'verbose_name_plural': '04. External Services'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '01. Services'},
        ),
        migrations.AlterModelOptions(
            name='service_dependson_service',
            options={'verbose_name_plural': '03. Internal Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='service_externalservice',
            options={'verbose_name_plural': '05. External Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'verbose_name_plural': '06. Service Areas (settings)'},
        ),
        migrations.AlterModelOptions(
            name='servicedetails',
            options={'verbose_name_plural': '02. Service Versions'},
        ),
        migrations.AlterModelOptions(
            name='servicestatus',
            options={'ordering': ['order'], 'verbose_name_plural': '09. Service Status (settings)'},
        ),
        migrations.AlterModelOptions(
            name='servicetrl',
            options={'ordering': ['order'], 'verbose_name_plural': '10. Service Technology Readiness Level (settings)'},
        ),
        migrations.AlterModelOptions(
            name='usercustomer',
            options={'verbose_name_plural': '08. Users / Customers of a Service'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name_plural': '07. User Roles (settings)'},
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='competitors',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_external',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_internal',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='funders_for_service',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='request_procedures',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='risks',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='value_to_customer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='features_current',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='features_future',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='use_cases',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='value',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usercustomer',
            name='role',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
