# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20170927_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(default='/var/www/html/agora/static/img/logos/logo-none.jpg', upload_to='/home/thanasis/agora/static/img/logos'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='icon',
            field=models.ImageField(default='/var/www/html/agora/static/img/logos/logo-none.jpg', upload_to='/home/thanasis/agora/static/img/logos'),
        ),
    ]
