# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20171017_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(default='/var/www/html/agora/static/img/logos/logo-none.jpg', upload_to='/srv/agora/static/img/logos'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='icon',
            field=models.ImageField(default='/var/www/html/agora/static/img/logos/logo-none.jpg', upload_to='/srv/agora/static/img/logos'),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='status',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceStatus'),
        ),
    ]
