# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-09 11:40
from __future__ import unicode_literals

import common.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20180125_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='icon',
            field=models.ImageField(default=b'service-area-icon-default.jpg', upload_to=common.helper.service_area_image_path),
        ),
    ]
