# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-09 11:40
from __future__ import unicode_literals

import common.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20180209_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(default=b'service-logo-default.png', upload_to=common.helper.service_image_path),
        ),
    ]
