# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-20 09:13
from __future__ import unicode_literals

import common.helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0016_auto_20180209_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(default=b'service-logo-default.jpg', upload_to=common.helper.service_image_path),
        ),
        migrations.AddField(
            model_name='serviceownership',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceownership',
            unique_together=set([('service', 'owner')]),
        ),
    ]
