# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20180328_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='customer_facing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
