# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20180328_1249'),
        ('service', '0018_serviceownership_state'),
    ]

    operations = [
    ]
