# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 10:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_service_organisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_mode', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('payment_model', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('pricing', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('conditions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('geo_availability', models.TextField(blank=True, default=None)),
                ('access_policy_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
