# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_accesspolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, unique=True),
        ),
    ]
