# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_auto_20190327_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='sla_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
