# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 11:57
from __future__ import unicode_literals

import common.helper
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_auto_20190328_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, unique=True)),
                ('webpage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('logo', models.ImageField(default=b'service-provider-logo-default.jpg', upload_to=common.helper.service_provider_image_path)),
                ('country', models.CharField(default=None, max_length=2)),
            ],
        ),
    ]
