# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 14:31
from __future__ import unicode_literals

import common.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_auto_20190402_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': '06. Service Categories (settings)'},
        ),
        migrations.AddField(
            model_name='service',
            name='service_categories',
            field=models.ManyToManyField(related_name='categories', to='service.ServiceCategory'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(default=b'service-category-icon-default.jpg', upload_to=common.helper.service_area_image_path),
        ),
    ]
