# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0037_auto_20190404_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceProvider',
            new_name='FederationMember',
        ),
    ]
