# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 10:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0037_auto_20190404_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='helpdesk',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='order_type',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='owner_contact',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='owner_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='security_contact',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='security_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='support_contact',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='support_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
