# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_auto_20190404_1156'),
        ('service', '0038_auto_20190404_1047'),
    ]

    operations = [
    ]
