# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0039_merge_20190404_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='maintenance_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='training_information',
            field=models.TextField(blank=True, default=None),
        ),
    ]
