# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0041_auto_20190405_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='changelog',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_update',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
