# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 09:35
from __future__ import unicode_literals

from django.db import migrations


def move_description(apps, schema_editor):
    Service = apps.get_model('service', 'Service')
    for s in Service.objects.all():
        if not s.short_description and s.description_external:
            s.short_description = s.description_external
            s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0043_servicedetails_service_trl'),
    ]

    operations = [
        migrations.RunPython(move_description),
    ]
