# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-29 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AditionalUsernames',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': '2. Contact Informations',
            },
        ),
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.ContactInformation')),
            ],
            options={
                'verbose_name_plural': '3. External Contacts',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, unique=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('department', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Institutions',
            },
        ),
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.ContactInformation')),
            ],
            options={
                'verbose_name_plural': '2. Internal Contacts',
            },
        ),
        migrations.CreateModel(
            name='ServiceOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('id_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_service_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.Institution')),
            ],
            options={
                'verbose_name_plural': '1. Service Owners',
            },
        ),
        migrations.AddField(
            model_name='aditionalusernames',
            name='id_service_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.ServiceOwner'),
        ),
    ]
