# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20190121_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='external',
            options={},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceowner',
            options={},
        ),
    ]
