# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_organisation_pd_bai_3_legal_entity'),
        ('owner', '0003_auto_20190618_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='url',
            new_name='position',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='organisation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.Organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
