# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20200427_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='first_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='last_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
