# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_auto_20200528_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
