# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20200605_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aditionalusernames',
            name='id_service_owner',
        ),
    ]
