# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_remove_aditionalusernames_id_service_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceowner',
            name='id_service_owner',
        ),
    ]
