# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_remove_serviceowner_id_service_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AditionalUsernames',
        ),
        migrations.RemoveField(
            model_name='external',
            name='id_contact_info',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.RemoveField(
            model_name='internal',
            name='id_contact_info',
        ),
        migrations.DeleteModel(
            name='External',
        ),
        migrations.DeleteModel(
            name='Internal',
        ),
    ]
