# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20200720_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
