# COLUMNS = ('collection', 'action', 'role', 'filter', 'check' 'fields', 'comment')
def get_rules():
    rules = [

        ('api/v2/custom-users', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'retrieve', 'serviceadmin', 'me', '*', '*', '*'),
        ('api/v2/custom-users', 'update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'update', 'admin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'partial_update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'partial_update', 'admin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/custom-users', 'delete', 'superadmin', '*', '*', '*', '*'),

        ('api/v2/service-admins', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/service-admins', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/service-admins', 'list', 'serviceadmin', 'manages_or_self_pending', '*', '*', '*'),
        ('api/v2/service-admins', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/service-admins', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/service-admins', 'retrieve', 'serviceadmin', '*', 'is_involved', '*', '*'),
        ('api/v2/service-admins', 'create', 'superadmin', '*', 'check_create_other', 'service,admin', '*'),
        ('api/v2/service-admins', 'create', 'admin', '*', 'check_create_other', 'service,admin', '*'),
        ('api/v2/service-admins', 'create', 'serviceadmin', '*', 'check_create_self', 'service', '*'),
        ('api/v2/service-admins', 'partial_update', 'superadmin', '*', 'check_update', 'state', '*'),
        ('api/v2/service-admins', 'partial_update', 'admin', '*', 'check_update', 'state', '*'),
        ('api/v2/service-admins', 'partial_update', 'serviceadmin', 'manages', 'check_update', 'state', '*'),
        ('api/v2/service-admins', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/service-admins', 'delete', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/service-admins', 'destroy', 'serviceadmin', '*', 'self_pending', '*', '*'),
        ('api/v2/service-admins', 'delete', 'serviceadmin', '*', 'self_pending', '*', '*'),

        ('api/v2/resource-admins', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/resource-admins', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/resource-admins', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/resource-admins', 'retrieve', 'admin', '*', '*', '*', '*'),

        ('api/v2/contact-information', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'list', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'list', 'observer', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'retrieve', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'retrieve', 'observer', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'create', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'create', 'admin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'update', 'admin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'partial_update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'partial_update', 'admin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/contact-information', 'delete', 'superadmin', '*', '*', '*', '*'),

        ('api/v2/providers', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/providers', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/providers', 'list', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/providers', 'list', 'observer', '*', '*', '*', '*'),
        ('api/v2/providers', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/providers', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/providers', 'retrieve', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/providers', 'retrieve', 'observer', '*', '*', '*', '*'),
        ('api/v2/providers', 'create', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/providers', 'create', 'admin', '*', '*', '*', '*'),
        ('api/v2/providers', 'update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/providers', 'update', 'admin', '*', '*', '*', '*'),
        ('api/v2/providers', 'partial_update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/providers', 'partial_update', 'admin', '*', '*', '*', '*'),
        ('api/v2/providers', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/providers', 'delete', 'superadmin', '*', '*', '*', '*'),

        ('api/v2/my-providers', 'list', 'serviceadmin', 'filter_belongs', '*', '*', '*'),
        ('api/v2/my-providers', 'retrieve', 'serviceadmin', '*', '*', '*', '*'),

        ('api/v2/resources', 'list', 'anonymous', '*', '*', '*', '*'),
        ('api/v2/resources', 'retrieve', 'anonymous', '*', '*', '*', '*'),
        ('api/v2/resources', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/resources', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/resources', 'list', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/resources', 'list', 'observer', '*', '*', '*', '*'),
        ('api/v2/resources', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/resources', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/resources', 'retrieve', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/resources', 'retrieve', 'observer', '*', '*', '*', '*'),
        ('api/v2/resources', 'create', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/resources', 'create', 'admin', '*', '*', '*', '*'),
        ('api/v2/resources', 'create', 'serviceadmin', '*', 'organisation_owned', '*', '*'),
        ('api/v2/resources', 'update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/resources', 'update', 'admin', '*', '*', '*', '*'),
        ('api/v2/resources', 'update', 'serviceadmin', '*', 'owned', '*', '*'),
        ('api/v2/resources', 'partial_update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/resources', 'partial_update', 'admin', '*', '*', '*', '*'),
        ('api/v2/resources', 'partial_update', 'serviceadmin', '*', 'owned', '*', '*'),
        ('api/v2/resources', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/resources', 'delete', 'superadmin', '*', '*', '*', '*'),

        ('api/v2/target-users', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'list', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'list', 'observer', '*', '*', '*', '*'),
        ('api/v2/target-users', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'retrieve', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'retrieve', 'observer', '*', '*', '*', '*'),
        ('api/v2/target-users', 'create', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'create', 'admin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'update', 'admin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'partial_update', 'admin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'partial_update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/target-users', 'delete', 'superadmin', '*', '*', '*', '*'),

        ('api/v2/affiliations', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'list', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'list', 'observer', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'retrieve', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'retrieve', 'observer', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'create', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'create', 'admin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'update', 'admin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'partial_update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'partial_update', 'admin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/affiliations', 'delete', 'superadmin', '*', '*', '*', '*'),

        ('api/v2/networks', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/networks', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/networks', 'list', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/networks', 'list', 'observer', '*', '*', '*', '*'),
        ('api/v2/networks', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/networks', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/networks', 'retrieve', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/networks', 'retrieve', 'observer', '*', '*', '*', '*'),
        ('api/v2/networks', 'create', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/networks', 'create', 'admin', '*', '*', '*', '*'),
        ('api/v2/networks', 'update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/networks', 'update', 'admin', '*', '*', '*', '*'),
        ('api/v2/networks', 'partial_update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/networks', 'partial_update', 'admin', '*', '*', '*', '*'),
        ('api/v2/networks', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/networks', 'delete', 'superadmin', '*', '*', '*', '*'),

        ('api/v2/structures', 'list', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/structures', 'list', 'admin', '*', '*', '*', '*'),
        ('api/v2/structures', 'list', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/structures', 'list', 'observer', '*', '*', '*', '*'),
        ('api/v2/structures', 'retrieve', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/structures', 'retrieve', 'admin', '*', '*', '*', '*'),
        ('api/v2/structures', 'retrieve', 'serviceadmin', '*', '*', '*', '*'),
        ('api/v2/structures', 'retrieve', 'observer', '*', '*', '*', '*'),
        ('api/v2/structures', 'create', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/structures', 'create', 'admin', '*', '*', '*', '*'),
        ('api/v2/structures', 'update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/structures', 'update', 'admin', '*', '*', '*', '*'),
        ('api/v2/structures', 'partial_update', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/structures', 'partial_update', 'admin', '*', '*', '*', '*'),
        ('api/v2/structures', 'destroy', 'superadmin', '*', '*', '*', '*'),
        ('api/v2/structures', 'delete', 'superadmin', '*', '*', '*', '*'),



    ]
    return rules
