

# Error codes
OWNER_NOT_FOUND = 1
SERVICE_NOT_FOUND = 2
INVALID_UUID = 3
SERVICE_COMPONENTS_IMPLEMENTATION_NONMATCHING_UUID = 4
SERVICE_COMPONENT_INVALID_UUID = 5
SERVICE_DETAILS_NOT_FOUND = 6
SERVICE_COMPONENT_NO_IMPLEMENTATIONS = 7
SERVICE_COMPONENT_NOT_FOUND = 8
SERVICE_COMPONENT_IMPLEMENTATION_INVALID_UUID = 9
SERVICE_COMPONENT_IMPLEMENTATION_DETAILS_NOT_FOUND = 10
SLA_INVALID_UUID = 11
SLA_NOT_FOUND = 12
SLA_SERVICE_DETAILS_MISMATCH = 13
SLA_PARAMETER_INVALID_UUID = 14
SERVICE_DETAILS_OPTIONS_NOT_FOUND = 15
PAGE_NOT_FOUND = 16
SLA_PARAMETER_NOT_FOUND = 17


# Info codes
SERVICE_OWNER_INSTITUTION = 1
SERVICE_OWNER_INFORMATION = 2
SERVICE_COMPONENTS_INFORMATION = 3
SERVICE_COMPONENT_IMPLEMENTATIONS_INFORMATION = 4
SERVICE_COMPONENT_IMPLEMENTATION_DETAILS = 5
SLA_INFORMATION = 6
SLA_PARAMETER_INFORMATION = 7
SERVICE_OPTIONS = 8