RULES = [
    ('api/v2/services', 'list', '*', '*', '*', '*'),
    ('api/v2/services', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/services', 'create', '*', '*', '*', '*'),
    ('api/v2/services', 'update', '*', '*', '*', '*'),
    ('api/v2/services', 'destroy', '*', '*', '*', '*'),

    ('api/v2/service-trls', 'list', '*', '*', '*', '*'),
    ('api/v2/service-trls', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/service-trls', 'create', '*', '*', '*', '*'),
    ('api/v2/service-trls', 'update', '*', '*', '*', '*'),
    ('api/v2/service-trls', 'destroy', '*', '*', '*', '*'),

    ('api/v2/service-areas', 'list', '*', '*', '*', '*'),
    ('api/v2/service-areas', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/service-areas', 'create', '*', '*', '*', '*'),
    ('api/v2/service-areas', 'update', '*', '*', '*', '*'),
    ('api/v2/service-areas', 'destroy', '*', '*', '*', '*'),

    ('api/v2/institutions', 'list', '*', '*', '*', '*'),
    ('api/v2/institutions', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/institutions', 'create', '*', '*', '*', '*'),
    ('api/v2/institutions', 'update', '*', '*', '*', '*'),
    ('api/v2/institutions', 'destroy', '*', '*', '*', '*'),

    ('api/v2/user-roles', 'list', '*', '*', '*', '*'),
    ('api/v2/user-roles', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/user-roles', 'create', '*', '*', '*', '*'),
    ('api/v2/user-roles', 'update', '*', '*', '*', '*'),
    ('api/v2/user-roles', 'destroy', '*', '*', '*', '*'),

    ('api/v2/user-customers', 'list', '*', '*', '*', '*'),
    ('api/v2/user-customers', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/user-customers', 'create', '*', '*', '*', '*'),
    ('api/v2/user-customers', 'update', '*', '*', '*', '*'),
    ('api/v2/user-customers', 'destroy', '*', '*', '*', '*'),

    ('api/v2/custom-users', 'list', '*', '*', '*', '*'),
    ('api/v2/custom-users', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/custom-users', 'create', '*', '*', '*', '*'),
    ('api/v2/custom-users', 'update', '*', '*', '*', '*'),
    ('api/v2/custom-users', 'destroy', '*', '*', '*', '*'),

    ('api/v2/service-owners', 'list', '*', '*', '*', '*'),
    ('api/v2/service-owners', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/service-owners', 'create', '*', '*', '*', '*'),
    ('api/v2/service-owners', 'update', '*', '*', '*', '*'),
    ('api/v2/service-owners', 'destroy', '*', '*', '*', '*'),

    ('api/v2/contact-information', 'list', '*', '*', '*', '*'),
    ('api/v2/contact-information', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/contact-information', 'create', '*', '*', '*', '*'),
    ('api/v2/contact-information', 'update', '*', '*', '*', '*'),
    ('api/v2/contact-information', 'destroy', '*', '*', '*', '*'),

    ('api/v2/contact_information_internal', 'list', '*', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'create', '*', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'update', '*', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'destroy', '*', '*', '*', '*'),

    ('api/v2/users', 'list', '*', '*', '*', '*'),
    ('api/v2/users', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/users', 'create', '*', '*', '*', '*'),
    ('api/v2/users', 'update', '*', '*', '*', '*'),
    ('api/v2/users', 'destroy', '*', '*', '*', '*'),

    ('api/v2/service-versions', 'list', '*', '*', '*', '*'),
    ('api/v2/service-versions', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/service-versions', 'create', '*', '*', '*', '*'),
    ('api/v2/service-versions', 'update', '*', '*', '*', '*'),
    ('api/v2/service-versions', 'destroy', '*', '*', '*', '*'),

    ('api/v2/service-status', 'list', '*', '*', '*', '*'),
    ('api/v2/service-status', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/service-status', 'create', '*', '*', '*', '*'),
    ('api/v2/service-status', 'update', '*', '*', '*', '*'),
    ('api/v2/service-status', 'destroy', '*', '*', '*', '*'),

    ('api/v2/components', 'list', '*', '*', '*', '*'),
    ('api/v2/components', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/components', 'create', '*', '*', '*', '*'),
    ('api/v2/components', 'update', '*', '*', '*', '*'),
    ('api/v2/components', 'destroy', '*', '*', '*', '*'),

    ('api/v2/component-implementations', 'list', '*', '*', '*', '*'),
    ('api/v2/component-implementations', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/component-implementations', 'create', '*', '*', '*', '*'),
    ('api/v2/component-implementations', 'update', '*', '*', '*', '*'),
    ('api/v2/component-implementations', 'destroy', '*', '*', '*', '*'),

    ('api/v2/component-implementation-details', 'list', '*', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'create', '*', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'update', '*', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'destroy', '*', '*', '*', '*'),

    ('api/v2/component-implementation-detail-link', 'list', '*', '*', '*', '*'),
    ('api/v2/component-implementation-detail-link', 'retrieve', '*', '*', '*', '*'),
    ('api/v2/component-implementation-detail-link', 'create', '*', '*', '*', '*'),
    ('api/v2/component-implementation-detail-link', 'update', '*', '*', '*', '*'),
    ('api/v2/component-implementation-detail-link', 'destroy', '*', '*', '*', '*'),
]
