RULES = [
    ('api/v2/services', 'list', 'admin', '*', '*', '*'),
    ('api/v2/services', 'list', 'observer', '*', '*', '*'),
    ('api/v2/services', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/services', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/services', 'create', 'admin', '*', '*', '*'),
    ('api/v2/services', 'update', 'admin', '*', '*', '*'),
    ('api/v2/services', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/services', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/service-trls', 'list', 'admin', '*', '*', '*'),
    ('api/v2/service-trls', 'list', 'observer', '*', '*', '*'),
    ('api/v2/service-trls', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/service-trls', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/service-trls', 'create', 'admin', '*', '*', '*'),
    ('api/v2/service-trls', 'update', 'admin', '*', '*', '*'),
    ('api/v2/service-trls', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/service-trls', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/service-areas', 'list', 'admin', '*', '*', '*'),
    ('api/v2/service-areas', 'list', 'observer', '*', '*', '*'),
    ('api/v2/service-areas', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/service-areas', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/service-areas', 'create', 'admin', '*', '*', '*'),
    ('api/v2/service-areas', 'update', 'admin', '*', '*', '*'),
    ('api/v2/service-areas', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/service-areas', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/institutions', 'list', 'admin', '*', '*', '*'),
    ('api/v2/institutions', 'list', 'observer', '*', '*', '*'),
    ('api/v2/institutions', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/institutions', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/institutions', 'create', 'admin', '*', '*', '*'),
    ('api/v2/institutions', 'update', 'admin', '*', '*', '*'),
    ('api/v2/institutions', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/institutions', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/user-roles', 'list', 'admin', '*', '*', '*'),
    ('api/v2/user-roles', 'list', 'observer', '*', '*', '*'),
    ('api/v2/user-roles', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/user-roles', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/user-roles', 'create', 'admin', '*', '*', '*'),
    ('api/v2/user-roles', 'update', 'admin', '*', '*', '*'),
    ('api/v2/user-roles', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/user-roles', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/user-customers', 'list', 'admin', '*', '*', '*'),
    ('api/v2/user-customers', 'list', 'observer', '*', '*', '*'),
    ('api/v2/user-customers', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/user-customers', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/user-customers', 'create', 'admin', '*', '*', '*'),
    ('api/v2/user-customers', 'update', 'admin', '*', '*', '*'),
    ('api/v2/user-customers', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/user-customers', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/custom-users', 'list', 'admin', '*', '*', '*'),
    ('api/v2/custom-users', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/custom-users', 'create', 'admin', '*', '*', '*'),
    ('api/v2/custom-users', 'update', 'admin', '*', '*', '*'),
    ('api/v2/custom-users', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/custom-users', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/service-owners', 'list', 'admin', '*', '*', '*'),
    ('api/v2/service-owners', 'list', 'observer', '*', '*', '*'),
    ('api/v2/service-owners', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/service-owners', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/service-owners', 'create', 'admin', '*', '*', '*'),
    ('api/v2/service-owners', 'update', 'admin', '*', '*', '*'),
    ('api/v2/service-owners', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/service-owners', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/contact-information', 'list', 'admin', '*', '*', '*'),
    ('api/v2/contact-information', 'list', 'observer', '*', '*', '*'),
    ('api/v2/contact-information', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/contact-information', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/contact-information', 'create', 'admin', '*', '*', '*'),
    ('api/v2/contact-information', 'update', 'admin', '*', '*', '*'),
    ('api/v2/contact-information', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/contact-information', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/contact_information_internal', 'list', 'admin', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'list', 'observer', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'create', 'admin', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'update', 'admin', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/contact_information_internal', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/users', 'list', 'admin', '*', '*', '*'),
    ('api/v2/users', 'list', 'observer', '*', '*', '*'),
    ('api/v2/users', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/users', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/users', 'create', 'admin', '*', '*', '*'),
    ('api/v2/users', 'update', 'admin', '*', '*', '*'),
    ('api/v2/users', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/users', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/service-versions', 'list', 'admin', '*', '*', '*'),
    ('api/v2/service-versions', 'list', 'observer', '*', '*', '*'),
    ('api/v2/service-versions', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/service-versions', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/service-versions', 'create', 'admin', '*', '*', '*'),
    ('api/v2/service-versions', 'update', 'admin', '*', '*', '*'),
    ('api/v2/service-versions', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/service-versions', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/service-status', 'list', 'admin', '*', '*', '*'),
    ('api/v2/service-status', 'list', 'observer', '*', '*', '*'),
    ('api/v2/service-status', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/service-status', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/service-status', 'create', 'admin', '*', '*', '*'),
    ('api/v2/service-status', 'update', 'admin', '*', '*', '*'),
    ('api/v2/service-status', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/service-status', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/components', 'list', 'admin', '*', '*', '*'),
    ('api/v2/components', 'list', 'observer', '*', '*', '*'),
    ('api/v2/components', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/components', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/components', 'create', 'admin', '*', '*', '*'),
    ('api/v2/components', 'update', 'admin', '*', '*', '*'),
    ('api/v2/components', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/components', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/component-implementations', 'list', 'admin', '*', '*', '*'),
    ('api/v2/component-implementations', 'list', 'observer', '*', '*', '*'),
    ('api/v2/component-implementations', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/component-implementations', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/component-implementations', 'create', 'admin', '*', '*', '*'),
    ('api/v2/component-implementations', 'update', 'admin', '*', '*', '*'),
    ('api/v2/component-implementations', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/component-implementations', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/component-implementation-details', 'list', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'list', 'observer', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'create', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'update', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-details', 'delete', 'admin', '*', '*', '*'),

    ('api/v2/component-implementation-detail-links', 'list', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-detail-links', 'list', 'observer', '*', '*', '*'),
    ('api/v2/component-implementation-detail-links', 'retrieve', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-detail-links', 'retrieve', 'observer', '*', '*', '*'),
    ('api/v2/component-implementation-detail-links', 'create', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-detail-links', 'update', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-detail-links', 'destroy', 'admin', '*', '*', '*'),
    ('api/v2/component-implementation-detail-links', 'delete', 'admin', '*', '*', '*'),
]
