# Populate db with initial data
echo populate meril domains...
python manage.py loaddata ./fixtures/meril_domains.json
echo populate meril subdomains...
python manage.py loaddata ./fixtures/meril_subdomains.json
echo populate legal statuses...
python manage.py loaddata ./fixtures/legal_statuses.json
echo populate networks...
python manage.py loaddata ./fixtures/networks.json
echo populate supercategories...
python manage.py loaddata ./fixtures/resource_supercategories.json
echo populate categories
python manage.py loaddata ./fixtures/resource_categories.json
echo populate subcategories
python manage.py loaddata ./fixtures/resource_subcategories.json
echo populating scientific domains...
python manage.py loaddata ./fixtures/scientific_domains.json
echo populating scientific subdomains...
python manage.py loaddata ./fixtures/scientific_subdomains.json
echo populating affiliations...
python manage.py loaddata ./fixtures/affiliations.json
echo populating areas of activity...
python manage.py loaddata ./fixtures/areas_of_activity.json
echo populating ESFRI domains...
python manage.py loaddata ./fixtures/esfridomains.json
echo populating ESFRI types...
python manage.py loaddata ./fixtures/esfritypes.json
echo populating societal grand challenges...
python manage.py loaddata ./fixtures/societal_grand_challenges.json
echo populating structure types...
python manage.py loaddata ./fixtures/structures.json
echo populating target users...
python manage.py loaddata ./fixtures/target_users.json
echo populating users...
python manage.py loaddata ./fixtures/users.json
echo populating order types...
python manage.py loaddata ./fixtures/order_types.json
echo populating funding bodies...
python manage.py loaddata ./fixtures/funding_bodies.json
echo populating funding programs...
python manage.py loaddata ./fixtures/funding_programs.json
echo populating access modes...
python manage.py loaddata ./fixtures/access_modes.json
echo populating access types...
python manage.py loaddata ./fixtures/access_types.json
echo populating TRLs...
python manage.py loaddata ./fixtures/trls.json
echo populating Resource Life Cycle Statuses...
python manage.py loaddata ./fixtures/resources_lcs.json
