# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-29 12:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, unique=True)),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('expression', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Parameters',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetailsOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceDetails')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
            ],
            options={
                'verbose_name_plural': '2. Service Options and Service Details Link',
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pricing', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Service Options',
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, unique=True)),
                ('service_option_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='options.ServiceOption')),
            ],
            options={
                'verbose_name_plural': '3. SLAs',
            },
        ),
        migrations.CreateModel(
            name='SLAParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.Parameter')),
                ('service_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.ServiceOption')),
                ('sla_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.SLA')),
            ],
            options={
                'verbose_name_plural': '5. SLA Parameters',
            },
        ),
        migrations.AddField(
            model_name='servicedetailsoption',
            name='service_options_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.ServiceOption'),
        ),
        migrations.AlterUniqueTogether(
            name='slaparameter',
            unique_together=set([('parameter_id', 'sla_id', 'service_option_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='servicedetailsoption',
            unique_together=set([('service_id', 'service_details_id', 'service_options_id')]),
        ),
    ]
