# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20170731_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicedetailsoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sla',
            options={},
        ),
        migrations.AlterModelOptions(
            name='slaparameter',
            options={},
        ),
    ]
