# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_auto_20190618_0930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicedetailsoption',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicedetailsoption',
            name='service_details_id',
        ),
        migrations.RemoveField(
            model_name='servicedetailsoption',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='servicedetailsoption',
            name='service_options_id',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='service_option_id',
        ),
        migrations.AlterUniqueTogether(
            name='slaparameter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='slaparameter',
            name='parameter_id',
        ),
        migrations.RemoveField(
            model_name='slaparameter',
            name='service_option_id',
        ),
        migrations.RemoveField(
            model_name='slaparameter',
            name='sla_id',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='ServiceDetailsOption',
        ),
        migrations.DeleteModel(
            name='ServiceOption',
        ),
        migrations.DeleteModel(
            name='SLA',
        ),
        migrations.DeleteModel(
            name='SLAParameter',
        ),
    ]
